config/routes.rb
Rails.application.routes.draw do
  resources :positions do
    resource :ratings
  end
  root 'positions#index'

end

app/models/characteristic.rb
class Characteristic < ActiveRecord::Base
  belongs_to :position
  has_one :rating
end

app/models/position.rb
class Position < ActiveRecord::Base
  has_many :characteristics

  accepts_nested_attributes_for :characteristics,
    :allow_destroy => true,
    :reject_if => :all_blank

  has_many :ratings, through: :characteristics
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :characteristic
  has_one :rating
  enum value: {rarely: 0, sometimes: 1, often: 2, consistently: 3, always: 4}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  def new
    @position = Position.new
    6.times {
      @position.characteristics.build
    }
  end

  def create
    @position = Position.new(position_params)
    if @position.save
      redirect_to positions_path
    else
      render :new
    end
  end

  def edit
    @position = Position.find(params[:id])
    3.times {
      @position.characteristics.build
    }
  end

  def update
    @position = Position.find(params[:id])
    if @position.update_attributes(position_params)
      redirect_to positions_path
    else
      render :edit
    end
  end

  def index
    ratings = {}
    ratings
    @positions = Position.all.map do |position|
      {
        name: position.name,
        id: position.id,
        ratings: position.characteristics.each_with_object({}) { |c, hash| hash[c.name] = Rating.values[c.rating.value] }
      }
    end
  end

  private

  def position_params
    params.require(:position).permit(:name, characteristics_attributes: [:id, :name, :description, :_destroy])
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def edit
    @position = Position.find(params[:position_id])
    @ratings = Rating.where(characteristic_id: @position.characteristics.map(&:id))
    characteristics = @position.characteristics.select{ |c| c.rating.nil? }
    characteristics.map{ |c| Rating.create(characteristic: c, value: :always)}
  end

  def update
    ratings_params.each do |rating_params|
      rating = Rating.find_or_initialize_by(characteristic_id: rating_params[:characteristic_id])
      rating.update(value: rating_params[:value].to_i)
    end

    redirect_to positions_path
  end

  private
  def ratings_params
    params.require(:ratings).values#.permit([:characteristic_id, :value])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WillStats</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/positions/_form.html.haml
= form_for(@position) do |f|
  = f.label(:name)
  = f.text_field(:name)
  %h2 Characteristics
  = f.fields_for :characteristics do |ff|
    %div
      = ff.label(:name)
      = ff.text_field(:name)
      = ff.label(:description)
      = ff.text_area(:description)
      - if ff.object.persisted?
        = ff.check_box :_destroy
        = ff.label :_destroy, "Destroy"
  = f.submit

app/views/positions/edit.html.haml
%h1 Edit Position
= render 'form'

app/views/positions/index.html.haml
%script{:src => "http://code.highcharts.com/highcharts.js"}
%script{:src => "http://code.highcharts.com/highcharts-more.js"}
%script{:src => "http://code.highcharts.com/modules/exporting.js"}
:css
  .position-chart {
    width: 550px;
    height: 400px;
    margin: 0 auto
    display: inline;
  }
  .position {
    border: 1px solid #555555;
    border-radius: 10px;
    padding: 10px;
    margin: 30px;
  }
:javascript
  var colorIndex = 0
  function stringToColour(str) {
    var colors = ['#7cb5ec', '#90ed7d',
   '#f15c80', '#2b908f', '#f45b5b', '#91e8e1']
    return colors[colorIndex++];
  };

  function chartIt(position) {
    var ratings = position['ratings'];
    $('#container-' + position['id']).highcharts({

      chart: {
        polar: true,
        type: 'line'
      },

      title: {
        text: position['name'],
        x: -80
      },

      pane: {
        size: '80%'
      },

      xAxis: {
        categories: Object.keys(ratings),
        tickmarkPlacement: 'on',
        lineWidth: 0
      },

      yAxis: {
        gridLineInterpolation: 'polygon',
        lineWidth: 0,
        min: 0,
        max: 4
      },

      tooltip: {
        shared: true,
        pointFormat: '<span style="color:{series.color}">{series.name}: <b>{point.y:,.0f}</b><br/>'
      },

      legend: {
        align: 'right',
        verticalAlign: 'top',
        y: 70,
        layout: 'vertical'
      },

      series: [{
        name: 'Will Read',
        type: 'area',
        color: stringToColour(position['name']),
        data: Object.keys(ratings).map(function(key){return ratings[key]}),
        pointPlacement: 'on'
      }]

    });
  };


= link_to("New Position", new_position_path)

- @positions.each do |position|
  .position
    %h1
      = position[:name]
    = link_to("Edit Characteristics", edit_position_path(position[:id]))
    = link_to("Edit Ratings", edit_position_ratings_path(position[:id]))
    .position-chart{id: "container-#{position[:id]}"}
    :javascript
      chartIt(#{position.to_json})

app/views/positions/new.html.haml
%h1 New Position
= render 'form'

app/views/ratings/edit.html.haml
%h1= @position.name
= form_tag position_ratings_path, method: "put" do |ff|
  - @ratings.each do |rating|
    = fields_for 'ratings[]', rating do |f|
      %div
        = rating.characteristic.name
        = f.select :value, options_for_select(Rating.values.collect { |name, int| [name.humanize, int] }, selected: Rating.values[rating.value])
        = f.hidden_field :characteristic_id
  = submit_tag